-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:LG Electronics LG Ultra HD 0x0003D3C4",
  mode = "3840x2160@60.00",
  position = "198x-1728",
  scale = 1.25,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:LG Electronics LG ULTRAGEAR 212NTWG2T457",
  mode = "2560x1440@143.97",
  position = "3440x-798",
  scale = 1,
  transform = 3,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:LG Electronics LG ULTRAGEAR 512TYTY08009",
  mode = "3440x1440@240.00",
  position = "0x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})
